development:
  clients:
    default:
      database: transilienwall
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: transilienwall
      hosts:
        - localhost:27017